数据类型：
1.   0d：标量，纯数。
2.   1d：向量，[1,2,3,4]
3.   2d：矩阵，[[1,2,3,4],[5,6,7,8]] ==>2rows, 4cols.
4.   3d：rgb图片，[[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]]==>channels=2, 2rows + 3cols
5.   4d：batch-rgb图片，n(batch-size) * channels * 矩阵

In [12]:
import torch
x = torch.arange(12)
x #tensor表示数值组成的数组，这个数组可能有多个 维度

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape #长为12的向量
x.reshape(3,4) #reshape函数改变成为3行4列的矩阵，2维

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((1,2,3)) #全0或者全1的3维tensor
torch.ones((1,2,3))
torch.tensor([[1,2,3,4],[4,5,6,7],[3,4,5,5]]) #python-list变量嵌套创建tensor

tensor([[1, 2, 3, 4],
        [4, 5, 6, 7],
        [3, 4, 5, 5]])

In [18]:
x = torch.tensor([1.0,2,3]) #浮点数
y = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(y)
z = torch.tensor([[1,2,3,4],[3,4,4,5],[2,2,3,4]])
torch.cat((y,z), dim=0) , torch.cat((y,z), dim=1) #分别在 0 和 1 维连接向量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  4.,  4.,  5.],
         [ 2.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  3.,  4.,  4.,  5.],
         [ 8.,  9., 10., 11.,  2.,  2.,  3.,  4.]]))

In [31]:
x = torch.arange(12).reshape(2,2,3)
y = torch.tensor([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(x)
print(y)
torch.cat((x,y), dim=2) #2维处连接
torch.cat((x,y), dim=1)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[3, 3, 3],
         [4, 4, 4]]])


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 1,  1,  1],
         [ 2,  2,  2]],

        [[ 6,  7,  8],
         [ 9, 10, 11],
         [ 3,  3,  3],
         [ 4,  4,  4]]])

In [32]:
x = torch.arange(12).reshape(2,2,3)
x.sum() #求和变成了0维纯数

tensor(66)

In [35]:
#广播broadcasting，维度相同才可以操作，通过复制行列数将tensor变为可相加的格式
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)

a+b

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
#访问元素
x = torch.arange(12).reshape(3,4)
print(x)
x[-1], x[1:3],x[1:2]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[4, 5, 6, 7]]))

In [40]:
#元素赋值
x = torch.arange(12).reshape(3,4)
print(x)

x[0:2, :] = 12 #修改多个元素，与访问方式相同
print(x)

x[1,2] = 9 #修改1个元素
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])
tensor([[12, 12, 12, 12],
        [12, 12,  9, 12],
        [ 8,  9, 10, 11]])


In [45]:
#转化为numpy
x = torch.arange(12).reshape(3,4)

a = x.numpy()
b = torch.tensor(a)

print(type(a), type(b))

#大小为1的tensor转换为python标量
c = torch.tensor([3.5])
c, c.item(), float(c), int(c)

<class 'numpy.ndarray'> <class 'torch.Tensor'>


(tensor([3.5000]), 3.5, 3.5, 3)