线性代数：
1. 向量的长度：所有元素的平方求和再开根号
2. 矩阵乘法：将向量在空间上“扭曲”
3. 特征向量：矩阵做变换时方向不会被改变的向量（不一定每个矩阵都有）

In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x**y #指数运算，x的y次方

tensor([9.])

In [3]:
A = torch.arange(20).reshape(4,5)

A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [4]:
print(A.T)  #转置矩阵
A.shape

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])


torch.Size([4, 5])

In [5]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() #只有克隆才可以重新分配内存
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [6]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [7]:
a = torch.arange(20*2).reshape(2, 5, 4) # 2个 4*5大小的矩阵
a, a.sum(), a.sum(axis=0) #sum(axis=n) 意思是在第n维上面求和

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor(780),
 tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]))

In [8]:
a.sum(axis=[0,1]) # 两个维度求和 结果应该和第3个维度相同

tensor([180, 190, 200, 210])

In [14]:
suma = a.sum(axis = 0, keepdims = True) #在计算总和或平均时保持轴数不变
afalse = a.sum(axis=0)
a/suma, 

(tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
          [0.1429, 0.1667, 0.1875, 0.2059],
          [0.2222, 0.2368, 0.2500, 0.2619],
          [0.2727, 0.2826, 0.2917, 0.3000],
          [0.3077, 0.3148, 0.3214, 0.3276]],
 
         [[1.0000, 0.9545, 0.9167, 0.8846],
          [0.8571, 0.8333, 0.8125, 0.7941],
          [0.7778, 0.7632, 0.7500, 0.7381],
          [0.7273, 0.7174, 0.7083, 0.7000],
          [0.6923, 0.6852, 0.6786, 0.6724]]]),)

In [29]:
ar = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(A.shape , ar.shape)
B = torch.ones(4, 3)
torch.mv(A, ar)  ,torch.mm(A, B) 
#矩阵*向量          #矩阵*矩阵

torch.Size([5, 4]) torch.Size([4])


(tensor([ 20.,  60., 100., 140., 180.]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [31]:
matrix = torch.arange(6).reshape(2, 3)
#对于matrix， 它是一个矩阵，行2 * 列3； 维度为2 。 
# 那么它有两个轴，0轴为行 (长度为3) 、1轴为列（长度为2）

print(matrix)
matrix.sum(axis=0), matrix.sum(axis=1)

tensor([[0, 1, 2],
        [3, 4, 5]])


(tensor([3, 5, 7]), tensor([ 3, 12]))